import type { Config } from "tailwindcss";
import * as tokens from "@openboat/design";

const config: Config = {
  content: ["./src/app/**/*.{js,ts,jsx,tsx,mdx}", "./src/components/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        navy: tokens.navy,
        gold: tokens.gold,
        teal: tokens.teal,
        amber: tokens.amber,
        ink: tokens.ink,
        muted: tokens.muted,
        faint: tokens.faint,
        surface: tokens.surface,
        fill: tokens.fill,
        hairline: tokens.hairline,
        "card-border": tokens.cardBorder,
        success: tokens.success,
        warning: tokens.warning,
        disabled: tokens.disabled,
        // ── Consumer booking flow design system ──────────────────────────────
        hull: { DEFAULT: "#16354a", "2": "#1c4260", line: "#3c5867" },
        deck: { DEFAULT: "#eef1f0", "2": "#e6eaea", "3": "#f6f8f8" },
        rule: { DEFAULT: "#cdd6da", soft: "#e3e9eb" },
        "border-input": "#9aa8ae",
        orange: {
          DEFAULT: "#c94510",
          ink: "#b1440f",
          press: "#8c3b12",
          light: "#ff8a5c",
        },
        "ink-2": "#41565f",
        "ink-3": "#5b6f79",
        "ink-dark-2": "#b6c6ce",
        "ink-dark-3": "#c9d6dd",
        "green-open": "#186a4a",
        // ── Admin console redesign ("Merchant" direction, design_handoff_admin_console) ──
        merchant: {
          ink: "#303030",
          page: "#f1f1f1",
          surface: "#ffffff",
          chrome: "#1a1a1a",
          "chrome-mid": "#303030",
          "chrome-light": "#4a4a4a",
          hairline: "#e3e3e3",
          control: "#d0d0d0",
          input: "#8a8a8a",
          muted: "#616161",
          faint: "#8a8a8a",
          disabled: "#b5b5b5",
          fill: "#fafafa",
          "fill-2": "#f6f6f7",
          "fill-3": "#f1f1f1",
          blue: "#005bd3",
          "blue-tint": "#e0f0ff",
          "blue-deep": "#00449e",
          green: "#0c5132",
          "green-tint": "#cdfee1",
          amber: "#ffb800",
          "amber-tint": "#ffd6a4",
          "amber-soft": "#fff1e3",
          "amber-deep": "#5e4200",
          red: "#8e1f0b",
          "red-tint": "#fee9e8",
          teal: "#e3f5f5",
        },
      },
      fontFamily: {
        grotesk: ["var(--font-space-grotesk)", "sans-serif"],
        jakarta: ["var(--font-plus-jakarta)", "sans-serif"],
        manrope: ["var(--font-manrope)", "sans-serif"],
        // Consumer booking flow
        archivo: ["var(--font-archivo)", "Helvetica", "sans-serif"],
        "plex-mono": ["var(--font-ibm-plex-mono)", "monospace"],
      },
      fontSize: {
        "9": "9px",
        "10": "10px",
        "11": "11px",
        "12": "12px",
        "13": "13px",
        "14": "14px",
        "15": "15px",
        "16": "16px",
        "17": "17px",
        "18": "18px",
        "19": "19px",
        "20": "20px",
        "21": "21px",
        "22": "22px",
        "24": "24px",
        "26": "26px",
        "27": "27px",
        "28": "28px",
        "30": "30px",
        "32": "32px",
        "34": "34px",
        "36": "36px",
        "48": "48px",
      },
      borderWidth: {
        "1.5": "1.5px",
      },
      borderRadius: {
        card: "20px",
        btn: "16px",
        pill: "999px",
        badge: "6px",
        icon: "10px",
      },
      spacing: {
        navbar: "60px",
        masthead: "66px",
        logo: "34px",
      },
      letterSpacing: {
        label: "0.08em",
        caps: "0.1em",
      },
      backdropBlur: {
        glass: "14px",
      },
      boxShadow: {
        card: "0 1px 2px rgba(16,32,31,0.04)",
        "card-selected": "0 14px 30px -14px rgba(201,154,63,0.35)",
        "day-selected": "0 8px 18px -6px rgba(20,35,61,0.4)",
        summary: "0 14px 40px -20px rgba(16,32,31,0.25)",
        hero: "0 20px 60px -10px rgba(20,35,61,0.5)",
        sidebar: "0 10px 30px rgba(20,35,60,0.08)",
      },
    },
  },
  plugins: [],
};

export default config;
